### ISSUE TITLE
Error running all_in_one.py script on mac osx 10.9 with python 3.4.3

### ISSUE THREAD

**Issue by leonh** [Eyepea/API-Hour#1]
Just kicking the tyres on your project...which seems really interesting btw. 

To try things out I ran the **all_in_one.py** script in the examples directory but was getting errors from gunicorn 
    

    ....
    File "/Users/leon/envs/midi-sequencer/lib/python3.4/site-packages/gunicorn/config.py", line 58, in __getattr__
    raise AttributeError("No configuration setting for: %s" % name)      
    AttributeError: No configuration setting for: debug

Providing a default for Gunicorn's debug setting seems to fix things for me.
This is what I added
https://github.com/leonh/API-Hour/commit/259e8eeddd3004517598b09af5200b4d562adc2e

**Comment by GMLudo** [comment]
Hi @leonh, thank you for your bug report.
It's because the latest version of gunicorn has removed debug setting.
I've fixed that in source code and documentation.
