### ISSUE TITLE
Compare with Aiohttp + gunicorn

### ISSUE THREAD

**Issue by nhumrich** [Eyepea/API-Hour#7]
Is there any performance advantage to using this over just normal aiohttp + gunicorn? Maybe the readme could provide benchmarks comparing it to a normal aiohttp stack as well

**Comment by GMLudo** [comment]
No efficiency advantages, it's the same solution for aiohttp and at Eyepea, we use aiohttp for the HTTP part with API-Hour.
The interest of API-Hour is the capability to transform any AsyncIO server to multi-worker pattern, not only aiohttp library. You can have a SMTP, SIP, SSH, HTTP... daemon in multi-worker mode.
